### PR TITLE
FaltMap: Add detailed example with explanation.

### PR DESCRIPTION
**Pull request by MRTHAKER**
This example will help in understanding the exact difference between FlatMap and map.

### CODE REVIEW

**Review by p7nov — CHANGES_REQUESTED** [review]
Hey!
Thanks for this addition, this is a really good example!
Please see and commit my suggestions on the code and text formatting. They make your addition follow [Kotlin coding conventions](https://kotlinlang.org/docs/coding-conventions.html) and documentation guidelines.

**Comment by p7nov** [comment]
Hey @MRTHAKER! Do you plan to update this PR?

**Comment by MRTHAKER** [comment]
> Hey @MRTHAKER! Do you plan to update this PR?

sorry for delay i got caught up in other work and forgot to add changes, will apply changes right now.

**Comment by MRTHAKER** [comment]
@p7nov 

> Hey @MRTHAKER! Do you plan to update this PR?

i have just pushed the changes.

**Review by p7nov — APPROVED** [review]

**Comment by p7nov** [comment]
Thank you for this update!

**Pull request merged**
